apiVersion: v1
kind: Service
metadata:
  name: java
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /mythaistar/$2
    kubernetes.io/ingress.class: ingress-public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - https://mts-devonfw-core.cloud.okteto.net/restaurant
  rules:
  - host: https://mts-devonfw-core.cloud.okteto.net/restaurant
    http:
      paths:
      - path: /api(/)(.*)
        backend:
          serviceName: java
          servicePort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: angular
  annotations:
    kubernetes.io/ingress.class: ingress-public
spec:
  tls:
  - hosts:
    - https://mts-devonfw-core.cloud.okteto.net/restaurant
  rules:
  - host: https://mts-devonfw-core.cloud.okteto.net/restaurant
    http:
      paths:
      - path: /
        backend:
          serviceName: angular
          servicePort: 8080
