apiVersion: v1
kind: Service
metadata:
  name: alb
  labels:
    env: dev
  ports:
  - port: 80
  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /mythaistar/$2
    kubernetes.io/ingress.class: ingress-public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  type: LoadBalancer
  tls:
  - hosts:
    - https://mts-devonfw-core.cloud.okteto.net/restaurant
  rules:
  - host: https://mts-devonfw-core.cloud.okteto.net/restaurant
    http:
      paths:
      - path: /api(/)(.*)
        backend:
          serviceName: java
          servicePort: 8081
          selector:
             env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: alb
   labels:
      env: dev
  annotations:
    kubernetes.io/ingress.class: ingress-public
spec:
type: LoadBalancer
  tls:
  - hosts:
    - https://mts-devonfw-core.cloud.okteto.net/restaurant
  rules:
  - host: https://mts-devonfw-core.cloud.okteto.net/restaurant
    http:
      paths:
      - path: /
        backend:
          serviceName: angular
          servicePort: 8080
        selector:
          env: dev
